--  The total sales generated by employee shipments, but only for orders that weigh more than 30 lbs.

select sum(final_cost) as total_employee_sales
from shipping_orders
join customers
on customers.customer_id = shipping_orders.customer_id
where is_employee = 1 and weight_lbs > 30;